POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
    "email": "user@mn.com",
    "username": "user3",
    "password": "passwwors1",
    "first_name": "user6first",
    "last_name": "user6last"
}

###
GET http://127.0.0.1:8000/api/components/
Content-Type: application/json
Authorization: Token 786e678509044550e03d6adf1af2c4c3b28b7d9d



###
GET http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization: Token 786e678509044550e03d6adf1af2c4c3b28b7d9d

###
POST http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization: Token 786e678509044550e03d6adf1af2c4c3b28b7d9d

{
    "ingredients":[
        {
        "id": 1,
        "amount": 10}
    ],
    "tags":[
        {
            "id": 2
        }
    ],
    "name": "wohou",
    "text": "text wohou",
    "cooking_time": 4040
}

###
GET http://127.0.0.1:8000/api/recipes/1/
Content-Type: application/json
Authorization: Token 786e678509044550e03d6adf1af2c4c3b28b7d9d


###
GET http://127.0.0.1:8000/api/loaddata/
Content-Type: application/json
Authorization: Token 786e678509044550e03d6adf1af2c4c3b28b7d9d

###
GET http://127.0.0.1:8000/api/tags/
Content-Type: application/json
Authorization: Token 786e678509044550e03d6adf1af2c4c3b28b7d9d


###
GET http://127.0.0.1:8000/api/users/
Authorization: Token 786e678509044550e03d6adf1af2c4c3b28b7d9d


###
POST http://127.0.0.1:8000/api/token/login/
Content-Type: application/json

{
    "username": "admin",
    "password": "adadad"
}

###
POST http://127.0.0.1:8000/users/token/logout/
Authorization: Token 786e678509044550e03d6adf1af2c4c3b28b7d9d

###
POST http://127.0.0.1:8000/users/users/set_password/
Authorization: Token 786e678509044550e03d6adf1af2c4c3b28b7d9d
Content-Type: application/json

{
    "new_password": "adadad",
    "current_password": "1ad1ad1ad"
}

###
GET http://127.0.0.1:8000/api/users/subscriptions/
Content-Type: application/json
Authorization: Token 786e678509044550e03d6adf1af2c4c3b28b7d9d

###
GET http://127.0.0.1:8000/api/users/3/subscribe/
Content-Type: application/json
Authorization: Token 786e678509044550e03d6adf1af2c4c3b28b7d9d

###
DELETE http://127.0.0.1:8000/api/users/3/subscribe/
Content-Type: application/json
Authorization: Token 786e678509044550e03d6adf1af2c4c3b28b7d9d


###
GET http://127.0.0.1:8000/api/users/me/
Content-Type: application/json
Authorization: Token 786e678509044550e03d6adf1af2c4c3b28b7d9d



###
GET http://127.0.0.1:8000/api/ingredients/
Content-Type: application/json
Authorization: Token 786e678509044550e03d6adf1af2c4c3b28b7d9d
