POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
    "email": "user@mn.com",
    "username": "user1",
    "password": "passwwors1",
    "first_name": "user6first",
    "last_name": "user6last"
}

###
GET http://127.0.0.1:8000/api/components/
Content-Type: application/json
Authorization: Token 061bf1595d6641d2ed1323d3058277c460e5f70f



###
GET http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization: Token 061bf1595d6641d2ed1323d3058277c460e5f70f

###
GET http://127.0.0.1:8000/api/loaddata/
Content-Type: application/json
Authorization: Token 061bf1595d6641d2ed1323d3058277c460e5f70f

###
GET http://127.0.0.1:8000/api/tags/
Content-Type: application/json
Authorization: Token 061bf1595d6641d2ed1323d3058277c460e5f70f


###
GET http://127.0.0.1:8000/api/users/
Authorization: Token 061bf1595d6641d2ed1323d3058277c460e5f70f


###
POST http://127.0.0.1:8000/api/token/login/
Content-Type: application/json

{
    "username": "admin",
    "password": "adadad"
}

###
POST http://127.0.0.1:8000/users/token/logout/
Authorization: Token 061bf1595d6641d2ed1323d3058277c460e5f70f

# ###
# admin token

# auth_token": "061bf1595d6641d2ed1323d3058277c460e5f70f

# ###
###
POST http://127.0.0.1:8000/users/users/set_password/
Authorization: Token 061bf1595d6641d2ed1323d3058277c460e5f70f
Content-Type: application/json

{
    "new_password": "adadad",
    "current_password": "1ad1ad1ad"
}

###
GET http://127.0.0.1:8000/api/users/subscriptions/
Content-Type: application/json
Authorization: Token 061bf1595d6641d2ed1323d3058277c460e5f70f

###
GET http://127.0.0.1:8000/api/users/3/subscribe/
Content-Type: application/json
Authorization: Token 061bf1595d6641d2ed1323d3058277c460e5f70f

###
DELETE http://127.0.0.1:8000/api/users/3/subscribe/
Content-Type: application/json
Authorization: Token 061bf1595d6641d2ed1323d3058277c460e5f70f


###
GET http://127.0.0.1:8000/api/users/me/
Content-Type: application/json
Authorization: Token 061bf1595d6641d2ed1323d3058277c460e5f70f



###
GET http://127.0.0.1:8000/api/ingredients/
Content-Type: application/json
Authorization: Token 061bf1595d6641d2ed1323d3058277c460e5f70f
