# Generated by Django 2.2 on 2021-09-18 07:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.IntegerField(validators=[api.models.validate_int_field])),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('measurement_unit', models.CharField(max_length=50, verbose_name='measurement unit')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='image')),
                ('text', models.TextField(blank=True, verbose_name='text')),
                ('cooking_time', models.IntegerField(default=1, validators=[api.models.validate_int_field], verbose_name='cooking time')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('color', models.CharField(max_length=7, verbose_name='color')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
        ),
    ]
