# Generated by Django 2.2 on 2021-09-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210919_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='ammount',
            new_name='amount',
        ),
    ]
