POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
    "email": "user1@user.com",
    "username": "user1",
    "password": "user5tg6yh",
    "first_name": "user1first",
    "last_name": "user1last"
}

###
GET http://127.0.0.1:8000/api/components/
Content-Type: application/json
Authorization: Token 64e3033c5c202bd461f3c5a61e3afc89905fb47b



###
GET http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization: Token 64e3033c5c202bd461f3c5a61e3afc89905fb47b

###
POST http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization: Token 64e3033c5c202bd461f3c5a61e3afc89905fb47b

{
    "ingredients":[
        {
        "id": 123,
        "amount": 11}
    ],
    "tags":[
            2
    ],
    "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
    "name": "ddfdfdfd",
    "text": "ddfdfdfd wohou",
    "cooking_time": 4040
}

###
GET http://127.0.0.1:8000/api/recipes/2/
Content-Type: application/json
Authorization: Token 64e3033c5c202bd461f3c5a61e3afc89905fb47b

###
GET http://127.0.0.1:8000/api/recipes/1/shopping_cart/
Content-Type: application/json
Authorization: Token 64e3033c5c202bd461f3c5a61e3afc89905fb47b

###
GET http://127.0.0.1:8000/api/recipes/download_shopping_cart/
Content-Type: application/json
Authorization: Token 64e3033c5c202bd461f3c5a61e3afc89905fb47b


###
DELETE http://127.0.0.1:8000/api/recipes/2/shopping_cart/
Content-Type: application/json
Authorization: Token 64e3033c5c202bd461f3c5a61e3afc89905fb47b

###
GET http://127.0.0.1:8000/api/recipes/?tags=tag1&author=1&limit=2&page=2
Content-Type: application/json

###
GET http://127.0.0.1:8000/api/recipes/1/favorite/
Content-Type: application/json
Authorization: Token 64e3033c5c202bd461f3c5a61e3afc89905fb47b

###
DELETE http://127.0.0.1:8000/api/recipes/7/favorite/
Content-Type: application/json
Authorization: Token 64e3033c5c202bd461f3c5a61e3afc89905fb47b

###
PUT http://127.0.0.1:8000/api/recipes/6/
Content-Type: application/json
Authorization: Token 64e3033c5c202bd461f3c5a61e3afc89905fb47b

{
    "ingredients":[
        {
            "id": 10,
            "amount": 1},
        {
            "id": 20,
            "amount": 2
        }
    ],
    "tags":[
            1
    ],
    "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
    "name": "new1  wohou",
    "text": "new1 text wohou",
    "cooking_time": 29993
}

###
PATCH http://127.0.0.1:8000/api/recipes/6/
Content-Type: application/json
Authorization: Token 64e3033c5c202bd461f3c5a61e3afc89905fb47b

{
    "ingredients":[
        {
            "id": 10,
            "amount": 15566},
        {
            "id": 20,
            "amount": 25566
        }
    ],
    "tags":[
            1
    ],
    "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
    "name": "5566new1  wohou",
    "text": "5566new1 text wohou",
    "cooking_time": 5566
}


###
DELETE http://127.0.0.1:8000/api/recipes/1/
Content-Type: application/json
Authorization: Token 64e3033c5c202bd461f3c5a61e3afc89905fb47b


###
GET http://127.0.0.1:8000/api/loaddata/
Content-Type: application/json
Authorization: Token 64e3033c5c202bd461f3c5a61e3afc89905fb47b

###
GET http://127.0.0.1:8000/api/tags/
Content-Type: application/json
Authorization: Token 64e3033c5c202bd461f3c5a61e3afc89905fb47b


###
GET http://127.0.0.1:8000/api/users/
Content-Type: application/json
Authorization: Token 64e3033c5c202bd461f3c5a61e3afc89905fb47b


###
POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json

{
    "email": "ad@ad.ru",
    "password": "adadad"
}

###
POST http://127.0.0.1:8000/api/auth/token/logout/
Authorization: Token 64e3033c5c202bd461f3c5a61e3afc89905fb47b

###
POST http://127.0.0.1:8000/users/users/set_password/
Authorization: Token 64e3033c5c202bd461f3c5a61e3afc89905fb47b
Content-Type: application/json

{
    "new_password": "adadad",
    "current_password": "1ad1ad1ad"
}

###
GET http://127.0.0.1:8000/api/users/subscriptions/
Content-Type: application/json
Authorization: Token 64e3033c5c202bd461f3c5a61e3afc89905fb47b

###
GET http://127.0.0.1:8000/api/users/3/subscribe/
Content-Type: application/json
Authorization: Token 64e3033c5c202bd461f3c5a61e3afc89905fb47b

###
DELETE http://127.0.0.1:8000/api/users/3/subscribe/
Content-Type: application/json
Authorization: Token 64e3033c5c202bd461f3c5a61e3afc89905fb47b


###
GET http://127.0.0.1:8000/api/users/me/
Content-Type: application/json
Authorization: Token 64e3033c5c202bd461f3c5a61e3afc89905fb47b



###
GET http://127.0.0.1:8000/api/ingredients/?name=ваниль
Content-Type: application/json
Authorization: Token 64e3033c5c202bd461f3c5a61e3afc89905fb47b


###
GET http://127.0.0.1:8000/api/ingredients/179/
Content-Type: application/json
